### ISSUE TITLE
Python wheel release for 2.1.2 and differences between .cpp version

### ISSUE THREAD

**Issue by amirjamez** [IITH-Compilers/IR2Vec#112]
Using the latest main HEAD, we can build `2.1.2` on .cpp side whereas there are no python releases matching that [here](https://pypi.org/project/IR2Vec/). 

```
$ ./ir2vec --version
IR2Vec Version : 2.1.2
LLVM (http://llvm.org/):
  LLVM version 17.0.6
  Optimized build.
```
We have seen differences between a 2.1.2 (.cpp version) vs. 2.1.1 (python) output. Steps to reproduce using a test case under llvm:

```
python3 ir2vecFeatures.py -fa -p "llvm/test/Examples/IRTransforms/SimplifyCFG/tut-simplify-cfg1.ll" > ir2vec.csv"
IR2Vec/build/bin/ir2vec  -fa -o ir2vec.csv  -level p llvm/test/Examples/IRTransforms/SimplifyCFG/tut-simplify-cfg1.ll"
```

![image](https://github.com/IITH-Compilers/IR2Vec/assets/8922398/f2a216ab-1baf-4693-98b9-cf4cb67e562a)

Here is the output file with two rows:  
[ir2vec.csv](https://github.com/user-attachments/files/15959225/ir2vec.csv)

Is it on the to-do list? 

Thanks
- Amir

**Comment by svkeerthy** [comment]
Hi @amirjamez,

The `whl` files corresponding to the latest commit of the main branch are available in the artifacts generated by the `build wheels` action. You can get it [here](https://github.com/IITH-Compilers/IR2Vec/actions/runs/9264735392). Typically we push it to pypi when we release a version. We have an issue (#103) to track this.

Hope it helps!

Best,
Venkat

**Comment by amirjamez** [comment]
Thanks @svkeerthy ! However, I don't see any `aarch64` version in the list :(

**Comment by svkeerthy** [comment]
Hi @amirjamez,

We do not have our Python packages built to support Aarch64 as of now! But, I believe the code in 
`Manylinux2014_Compliant_Source` can be used to build `whl` files for Aarch64 with a little effort. Or, you can use the binaries/library in this case if it helps.

Thanks,
Venkat
