### ISSUE TITLE
Issue about error:expected type 

### ISSUE THREAD

**Issue by wangzhanBJCA** [IITH-Compilers/IR2Vec#130]
During the practice, I noticed some errors about specific ir instructions, such as :
![image](https://github.com/user-attachments/assets/a881413b-e903-45ba-8c2a-af7b24ba1b31)

![image](https://github.com/user-attachments/assets/2749f50b-a1ff-441d-b053-0650d6e5d1e0)

![image](https://github.com/user-attachments/assets/759822f1-c444-4397-9aad-542f0b6ee019)

![image](https://github.com/user-attachments/assets/647d2895-ca29-40e6-a3cb-56a4b58e02e0)

![image](https://github.com/user-attachments/assets/b450b607-97da-435d-92e6-73adbfec7131)

This is my ir2vec version
![image](https://github.com/user-attachments/assets/b94e3f6c-787c-4cc3-8b2f-12818c2d74c2)

Does ir2vec has plan to solve them ? And how could I resolve them in my procedure of usage? 

Thanks very much, hope for reply~

**Comment by svkeerthy** [comment]
Hi @wangzhanBJCA,

Any inputs on this?

**Comment by wangzhanBJCA** [comment]
Sorry for the late reply.  After some experiments, it seems to be caused by my down-stream modifications base on llvm-17.0.6, 

And I tested the official llvm-17.0.6 release package and ir2vec built by the same llvm version, everything is OK. 

This issue could be closed now, I think~

**Comment by svkeerthy** [comment]
Okay, thanks. If you want to try IR2Vec with your modified LLVM, you can set the `LT_LLVM_INSTALL_DIR` flag in the cmake, and it should work fine. 

Let me know if you have any questions.
