### ISSUE TITLE
Segmentation fault when using IR2vec

### ISSUE THREAD

**Issue by gloaming2dawn** [IITH-Compilers/IR2Vec#26]
I use IR2Vec to get features of some IR files (with LLVM 10.0.1), but it shows segmentation fault. Could you explain the reason about that? 
[McGill_chomp_531_32.zip](https://github.com/IITH-Compilers/IR2Vec/files/6320211/McGill_chomp_531_32.zip)

**Comment by gloaming2dawn** [comment]
I use the Flow-Aware representation

**Comment by svkeerthy** [comment]
Hi, Thanks for bringing this up.  This seems like a bug that was introduced in some refactoring.

**Comment by svkeerthy** [comment]
Hi @gloaming2dawn, Hope this issue is fixed now. Please feel free to reopen the issue if needed. Thanks!
