### ISSUE TITLE
Instruction level encoding

### ISSUE THREAD

**Issue by pedrofrancescon** [IITH-Compilers/IR2Vec#45]
Hello! 

Any intentions on also adding an option for generating instruction level encoding on the future as well? And by that I mean not like the `seedEmbeddingVocab-300-llvm12.txt` file but one that takes into account the whole instruction and not only the opcode, in a way that each unique instruction could have it's own feature/tensor representation.

If not, would you have any pointers on how this could be done, perhaps using `IR2Vec` itself as a base?

Thanks in advance!

**Comment by svkeerthy** [comment]
Hi,

You may need to design instruction level relations and incorporate changes in [CollectIR.cpp](https://github.com/IITH-Compilers/IR2Vec/blob/main/src/CollectIR.cpp) to process instructions, and modify [preprocess.py](https://github.com/IITH-Compilers/IR2Vec/blob/main/seed_embeddings/OpenKE/preprocess.py) to train for new triplets at instruction level to get an vocabulary for instructions.  This [README](https://github.com/IITH-Compilers/IR2Vec/tree/main/seed_embeddings) could help.

However, it might be hard to cover all possible instructions as LLVM IR allows almost all possible combinations of the entities. Please check [Sec 6.3](https://dl.acm.org/doi/fullHtml/10.1145/3418463#sec-36) of IR2Vec paper for details, if you are interested.

Best,
Venkat

**Comment by svkeerthy** [comment]
Closing this thread due to inactivity.  Please feel free to reopen if needed.

**Comment by pedrofrancescon** [comment]
After reading the paper now I better understand the issues and drawbacks involved in this task. Very good explanation on Sec. 6.3, it addresses exactly what I was looking for.

Thank you for your help!
Pedro.

**Comment by svkeerthy** [comment]
Great! Glad that it helped.

**Comment by svkeerthy** [comment]
Hi, 

Can you please give more details? Would you like to use the embeddings for instructions?

-Venkat
