### ISSUE TITLE
Interested in adding to CompilerGym?

### ISSUE THREAD

**Issue by ChrisCummins** [IITH-Compilers/IR2Vec#47]
Hi folks,

Great work!

Myself and a few other folks at Meta have been building [CompilerGym](https://github.com/facebookresearch/CompilerGym), a library of reinforcement learning environments for compiler optimization tasks. We have an LLVM environment that includes a number of different program representations for learning over, such as inst2vec and ProGraML. I think IR2Vec would be a good fit here, but I don't have enough bandwidth to work on it myself. Would you folks be interested in adding it? I can help with code pointers and review. Thanks!

Chris

**Comment by ChrisCummins** [comment]
BTW, feel free to weigh in on our discussion [here](https://github.com/facebookresearch/CompilerGym/issues/449).

**Comment by svkeerthy** [comment]
Hi Chris,

Apologies for the delay in response. Currently, we are also caught up with some deadlines. But, it would be very interesting to have IR2Vec support in CompilerGym. Currently, we support LLVM 8.x, 10.x and 12.x. We would be happy to look into it sometime if you could give some pointers on how it can be integrated. 

Best,
Venkat

**Comment by ChrisCummins** [comment]
Hi Venkat, awesome! We build against LLVM 10, it sounds like it should fit right in. How about we have a quick chat in a couple of weeks, or whens convenient for you, to go through the details? Good luck with your deadlines :)

Cheers,
Chris

**Comment by svkeerthy** [comment]
Sure, sounds good. Will ping you through mail.

**Comment by anilavakundu** [comment]
Done: [PR](https://github.com/facebookresearch/CompilerGym/pull/560). Pending to be merged. Closing this issue for now; @ChrisCummins  please feel free to reopen this if any input is needed from our side.
