### ISSUE TITLE
Update to cmake

### ISSUE THREAD

**Issue by anilavakundu** [IITH-Compilers/IR2Vec#54]
update cmake to support integration as an external dependency in any other cmake project

**Comment by m-atalla** [comment]
Hi,

Thank you for implementing this enhancement!

I've been experimenting with IR2Vec, and it seems that most of the development has been done on the `main` branch. Are there any plans to extend these updates to other branches?

Currently, I'm using the `llvm-16` branch, and I'd be happy to assist in updating that branch if you're accepting pull requests.

**Comment by svkeerthy** [comment]
Hi @m-atalla,

That would be really great! I can help merge them if you can raise a PR :)
